Added iou-tracker
amanchhaparia/Multi-Cam-ReID pull request #5
Opened 2022-06-22 16:39 UTC by Dhruv454000

2022-06-23 05:03 UTC, Dhruv454000 commented
@amanchhaparia except vectorization all things have been done.

2022-06-23 09:23 UTC, amanchhaparia requested changes
@Dhruv454000, Thanks for your work! 
Try to implement vectorized version to calculate IoU along with changes request, ping me once they are done.

2022-06-23 09:23 UTC, amanchhaparia commented on Trackers/iou_tracker/iou.py
> +        self.max_lost=10
Do not unnecessarily change the variable name, we will maintain the uniform naming throughout the code base.

2022-06-23 09:23 UTC, amanchhaparia commented on Trackers/iou_tracker/iou.py
> +        for i in matched:
Instead of using `i`, it is better to unpack it in `trk`, 'det' or any relevant variables so they self document their purpose.

2022-06-23 09:23 UTC, amanchhaparia commented on Trackers/iou_tracker/iou.py
> +
Remove unnecessary extra lines.

2022-06-23 09:23 UTC, amanchhaparia commented on main.py
> -
Do not remove the code from the main untill is redundant, its better to comment it out for now.

2022-06-24 08:05 UTC, amanchhaparia requested changes

2022-06-24 08:05 UTC, amanchhaparia commented on Trackers/iou_tracker/iou.py
> +        self.min_hits=3
Please follow the coding style for putting space before and after operators like `=` etc

2022-06-24 08:05 UTC, amanchhaparia commented on Trackers/iou_tracker/iou.py
> +        return tuple((orig_left, orig_top, orig_right, orig_bottom))
Try to put the utility functions below the methods which are important to logic of the code ie put this function after `get_iou_matrix`.

2022-06-24 10:38 UTC, amanchhaparia commented
@Dhruv454000, there is a minor merge conflict kindly resolve it.

2022-06-24 18:19 UTC, amanchhaparia approved these changes

2022-06-24 18:20 UTC, merged