Added utility module
amanchhaparia/Multi-Cam-ReID pull request #9
Opened 2022-06-25 10:00 UTC by shahpratham

This PR adds:
- utility module
- uses convert2relative() from `yolo.py`
- removed hard-coded values of image and model  height, width

2022-06-27 11:03 UTC, amanchhaparia requested changes
@shahpratham, Instead of converting the bbox multiple times just convert the bbox in the required form where it is generated.  Also this branch have some merge conflicts kindly resolve them too.

2022-06-28 19:28 UTC, shahpratham commented on Trackers/iou_tracker/iou.py
> +from Detectors.YOLO import yolo
yes sorry, mb.

2022-06-28 19:29 UTC, shahpratham commented on Trackers/utility/utility.py
> +        left, top, right, bottom =yolo.convert2relative(bbox)
yes, done

2022-06-28 19:29 UTC, shahpratham commented
@amanchhaparia please check now

2022-06-29 08:44 UTC, amanchhaparia requested changes
Remove unnecessary `print` statements.

2022-06-29 18:22 UTC, amanchhaparia approved these changes
@shahpratham, Thanks for your work!

2022-06-29 18:23 UTC, merged